### ISSUE TITLE
UWP Client Exception Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by MhAllan** [aspnet/SignalR#1294]
Using the nuget 1.0.0-alpha2-final, my code works on .net core console, fails with the above error on UWP.

Stack:

   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<SendInvocation>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeAsyncCore>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.<InvokeAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SignalR.Client.HubConnectionExtensions.<InvokeAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MyClient.<JoinMeeting>d__7.MoveNext()

Using the source code 7c635fae56268a434b4fbfdcdcfa65539a733640 the core console works, the UWP gets compiler error "Cannot find type System.Buffers.OwnedMemory`1 in module System.Memory.dll"

**Comment by anurse** [comment]
Can you try using one of our more recent nightly builds using the instructions here: https://github.com/aspnet/Home#builds ?

**Comment by MhAllan** [comment]
@anurse , I used the build you referenced, compiled and published nupkg, same error. the UWP is within Xamarin Forms solution by the way.

**Comment by BernardoGon** [comment]
Just in case it is of any use, I am running into the same issue, but it was working with 1.0.0-alpha1-final. When I changed to preview, I got the same error "Cannot find type System.Buffers.OwnedMemory`1 in module System.Memory.dll"

**Comment by mtirion** [comment]
I'm using the 1.0.0-rc1-final package from https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/ and get the exception: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

I'm using it in a blank UWP app, building for 17134 (Target and Min Version).

**Comment by anurse** [comment]
I'm not able to repro this in a UWP app. Would you be able to post a repro project on GitHub and link it? Getting a look at your csproj would help a lot.

**Comment by JamesNK** [comment]
@anurse Are you testing the UWP compiled as both debug and release? Release will do a AOT compile which is quite different.

**Comment by anurse** [comment]
Yep, I used Debug and Release. I did only try `x86` though, I can try `x64` and `ARM` to make sure those work too, since they might affect this.

**Comment by TonyHenrique** [comment]
I am also having this 
System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. 


My UWP app is compiled with both target and min version : Windows 10, version 1803 (10.0; Build 17134)

**Comment by davidfowl** [comment]
Sounds like you found the fix. You need at least a version that supports netstandard 2.0

**Comment by TonyHenrique** [comment]
If I build with all the latest versions, that Exception happens. Check it on your machine, on a UWP Project with 
Target version:
Windows 10, version 1803 (10.0; Build 17134)
and Min version:
Windows 10, version 1803 (10.0; Build 17134)

**Comment by mtirion** [comment]
Yes, going back for MinVersion to 16299 did it for me too. 

Thanks

**Comment by TonyHenrique** [comment]
I think that the issue is not only that. Look again, Does not SDK 17134 support  .NET Standard 2.0 ?
Seems like a bug.

**Comment by anurse** [comment]
Ah, I see, when you move the min up to 17134 it breaks. I'll try that, I may know what the issue is.

**Comment by davidfowl** [comment]
@anurse keep this open as a tracking issue like Xamarin.

**Comment by anurse** [comment]
Created a clearer tracking issue #2406 since we've identified the issue and have a corefx PR to track.
