### ISSUE TITLE
On Negotiation error from HTTP request. 0: undefined on Android React Native App

### ISSUE THREAD

**Issue by Shhzdmrz** [aspnet/SignalR#2254]
I am using SignalR with .NET Core since alpha version it was working fine until preview2 everything seems good but after RC1 I was trying to update my packages for Server and Client side I am not even able to connect to the websocket. I tried on the browser side and the client version working fine but on the android app it is not working.

this is my code for the app side to configure the connection:
```es6 
const options = { logger: LogLevel.Trace, transport: HttpTransportType.WebSockets };//,};
const conn = new HubConnectionBuilder().withUrl('http://192.168.0.132:34078/chat', options)
                                                                         .build();
```
I don't know what I am missing for the configuration because it is not even trigging any sort of request on server.

* Chat.cs
```C#
public class Chat : Hub
{
    public async Task Send(string message)
    {     
        await Clients.All.SendAsync("Send", message);
     }        
}
```

* Program.cs
```C#
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }
    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>();
    }
}
```
* Startup.cs
```C#
public void ConfigureServices(IServiceCollection services)
{
    services.AddCors(o => o.AddPolicy("CorsPolicy", builder =>
    {
        builder.AllowAnyMethod().AllowAnyHeader();
     }));
     services.AddSignalR();
}
public void Configure(IApplicationBuilder app)
{
    app.UseFileServer();
    app.UseCors("CorsPolicy");
    app.UseSignalR(routes =>
    {
        routes.MapHub<Chat>("/chat");
    });
}
```
* Versions of Server-Side NuGet Packages: 
```xml 
<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.0-rc1-final" />
<PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.0.0-rc1-final" />
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.4" />
<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.0-rc1-final" />
<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="2.8.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.8.0" />
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="2.8.0" />
<PackageReference Include="Newtonsoft.Json" Version="11.0.2" /> 
```
* Versions of Client-Side NuGet/NPM Packages: 
```json 
"@aspnet/signalr": "1.0.0-rc1-update1" 
```

* Are you using the C# client or the JavaScript client: 
```text 
Javascript (inside React Native app) 
```
* The Server you are using (Kestrel/HttpSysServer/IIS/IIS Express/Azure Web App/etc.): 
```text 
IIS Express 
```
* The Operating System on the Server (Windows/Linux/macOS): 
```text 
Windows 
```
* The Operating System on the Client (Windows/Linux/macOS): 
```text 
Windows and Android 
```
* The Browser on the client, if using the JavaScript client (IE/Chrome/Edge/Firefox/etc.): 
```text 
Chrome 
```
* If possible, please collect logs from the client: 
```text
*Debug: Starting connection with transfer format 'Text'. Utils.js:198 
*Debug: Sending negotiation request: http://192.168.0.132:34078/chat/negotiate Utils.js:198 
*Warning: Error from HTTP request. 0: undefined Utils.js:191  
console.warn @ YellowBox.js:80
ConsoleLogger.log @ Utils.js:191
xhr.onerror @ HttpClient.js:90
dispatchEvent @ event-target.js:172
setReadyState @ XMLHttpRequest.js:567
__didCompleteResponse @ XMLHttpRequest.js:397
(anonymous) @ XMLHttpRequest.js:503
emit @ EventEmitter.js:179
__callFunction @ MessageQueue.js:351
(anonymous) @ MessageQueue.js:116
__guardSafe @ MessageQueue.js:314
callFunctionReturnFlushedQueue @ MessageQueue.js:115
(anonymous) @ debuggerWorker.js:70
Show 11 more blackboxed frames
ExceptionsManager.js:71 Error: Failed to complete negotiation with the server: Error
reactConsoleErrorHandler @ ExceptionsManager.js:71
console.error @ YellowBox.js:69
ConsoleLogger.log @ Utils.js:188
(anonymous) @ HttpConnection.js:231
step @ HttpConnection.js:34
(anonymous) @ HttpConnection.js:15
rejected @ HttpConnection.js:7
tryCallOne @ core.js:37
(anonymous) @ core.js:123
(anonymous) @ JSTimers.js:295
_callTimer @ JSTimers.js:152
_callImmediatesPass @ JSTimers.js:200
callImmediates @ JSTimers.js:464
__callImmediates @ MessageQueue.js:327
(anonymous) @ MessageQueue.js:145
__guardSafe @ MessageQueue.js:314
flushedQueue @ MessageQueue.js:144
callFunctionReturnFlushedQueue @ MessageQueue.js:119
(anonymous) @ debuggerWorker.js:70
Show 13 more blackboxed frames
ExceptionsManager.js:71 Error: Failed to start the connection: Error
reactConsoleErrorHandler @ ExceptionsManager.js:71
console.error @ YellowBox.js:69
ConsoleLogger.log @ Utils.js:188
(anonymous) @ HttpConnection.js:192
step @ HttpConnection.js:34
(anonymous) @ HttpConnection.js:15
rejected @ HttpConnection.js:7
tryCallOne @ core.js:37
(anonymous) @ core.js:123
(anonymous) @ JSTimers.js:295
_callTimer @ JSTimers.js:152
_callImmediatesPass @ JSTimers.js:200
callImmediates @ JSTimers.js:464
__callImmediates @ MessageQueue.js:327
(anonymous) @ MessageQueue.js:145
__guardSafe @ MessageQueue.js:314
flushedQueue @ MessageQueue.js:144
callFunctionReturnFlushedQueue @ MessageQueue.js:119
(anonymous) @ debuggerWorker.js:70
Show 13 more blackboxed frames
App.js:54 Error
    at new HttpError (Errors.js:21)
    at XMLHttpRequest.xhr.onerror (HttpClient.js:91)
    at XMLHttpRequest.dispatchEvent (event-target.js:172)
    at XMLHttpRequest.setReadyState (XMLHttpRequest.js:567)
    at XMLHttpRequest.__didCompleteResponse (XMLHttpRequest.js:397)
    at XMLHttpRequest.js:503
    at RCTDeviceEventEmitter.emit (EventEmitter.js:179)
    at MessageQueue.__callFunction (MessageQueue.js:351)
    at MessageQueue.js:116
    at MessageQueue.__guardSafe (MessageQueue.js:314)
```
* If possible, please collect logs from the server: 
```text 
SignalRTest> Hosting environment: Development 
SignalRTest> Content root path: C:\Users\test\Documents\Visual Studio 2017\Projects\SignalRTest\SignalRTest 
SignalRTest> Now listening on: http://192.168.0.132:34078 
SignalRTest> Application started. Press Ctrl+C to shut down.
```

**Comment by BrennanConroy** [comment]
Your server is listening on http://127.0.0.1:31641 and your client is trying to connect to http://192.168.0.132:34078 those aren't the same ports

**Comment by Shhzdmrz** [comment]
But the web version working on the same http://192.168.0.132:34078 address.

**Comment by BrennanConroy** [comment]
From your logs:
Server:
> SignalRTest> Now listening on: http://127.0.0.1:31641 

Client:
> *Debug: Sending negotiation request: http://192.168.0.132:34078/Hubs/Chat/negotiate

**Comment by Shhzdmrz** [comment]
I also specified the address to be used  http://192.168.0.132:34078 but still having the same error.

I remember this error occured before when I was using the different version of the signalR for Server and Client. Is it ok to use `1.0.0-rc1-update1` for client and `1.0.0-rc1-final` for server?

**Comment by anurse** [comment]
> Is it ok to use 1.0.0-rc1-update1 for client and 1.0.0-rc1-final for server?

That's fine. There was a minor update to the JavaScript client but the server did not need to be updated.

**Comment by Shhzdmrz** [comment]
This PR #2242 solved my issue.

**Comment by BrennanConroy** [comment]
Closing as it appears to be fixed.

**Comment by Shhzdmrz** [comment]
@BrennanConroy have a look on this discussion https://github.com/aspnet/SignalR/pull/2242#issuecomment-393048746

**Comment by BrennanConroy** [comment]
Right, which is why I closed it

**Comment by Shhzdmrz** [comment]
So when this patch is releasing?

**Comment by anurse** [comment]
There's no official release date yet, we're working on getting it out this month though. There will be a public announcement on the [ASP.NET Blog](https://blogs.msdn.microsoft.com/webdev) when it is released. That's where you can expect to see announcements of specific release dates/roadmaps, when we have them.
